language: node_js
node_js:
 - "node"
script: yarn build
deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  fqdn: ui.emcasa.com
  on:
    branch: master

