language: node_js
sudo: required
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

install:
  - yarn
  - npm install -g lerna

script:
  - yarn build
  - yarn docz
  - >
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      echo "Publishing expo preview...";
      export EXP_PRIVACY=unlisted;
      export EXP_CHANNEL=$TRAVIS_PULL_REQUEST_BRANCH;
      export GIT_STATUS=true;
      lerna run publish-expo --scope @emcasa/storybook-native --stream;
    fi

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: lerna exec --no-private --bail=false -- "npm publish"
    on:
      tags: true
      repo: emcasa/ui
  - provider: script
    skip_cleanup: true
    keep-history: true
    script: lerna run publish-expo --scope @emcasa/storybook-native --stream
    on:
      branch: master
  - provider: pages
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: gh-pages
    fqdn: ui.emcasa.com
    on:
      branch: master
