language: node_js
node_js:
 - "node"
deploy:
  - provider: npm
    email: lucas.tulio@emcasa.com
    api_key:
      secure: $NPM_TOKEN
    on:
      tags: true
      repo: emcasa/ui
  - provider: pages
    script: yarn build
    local-dir: public
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: gh-pages
    fqdn: ui.emcasa.com
    on:
      branch: master
